# Generated by Django 2.1.1 on 2018-09-30 12:59

from django.db import migrations, models
import django.db.models.deletion
import holaserver.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarDetailsTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carType', models.CharField(choices=[('UNKNOWN', 1), ('CAR_TYPE_HATCHBACK', 2), ('CAR_TYPE_SEDAN', 3), ('CAR_TYPE_MINIVAN', 4), ('CAR_TYPE_AUTO', 5)], default='CarType.UNKNOWN', max_length=100)),
                ('carModel', models.CharField(max_length=50)),
                ('carLicense', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'CarDetailsTable',
            },
        ),
        migrations.CreateModel(
            name='CarStatusTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carType', models.CharField(choices=[('UNKNOWN', 1), ('CAR_TYPE_HATCHBACK', 2), ('CAR_TYPE_SEDAN', 3), ('CAR_TYPE_MINIVAN', 4), ('CAR_TYPE_AUTO', 5)], default='CarType.UNKNOWN', max_length=100)),
                ('carAvailability', models.CharField(choices=[('UNKNOWN', 1), ('CAR_OFF_DUTY', 2), ('CAR_AVAILABLE', 3), ('CAR_ON_TRIP', 4), ('CAR_ON_TRIP_CLOSE_TO_COMPLETION', 5)], default='CarAvailabilityStatus.UNKNOWN', max_length=100)),
                ('geoLocation', holaserver.models.GeoLocationField()),
            ],
            options={
                'verbose_name_plural': 'CarStatusTable',
            },
        ),
        migrations.CreateModel(
            name='CustomerTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('pastSevenDaysRideCount', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name_plural': 'CustomerTable',
            },
        ),
        migrations.CreateModel(
            name='DriverDetailsTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=10)),
                ('avg_rating', models.FloatField(default=0.0)),
                ('carId', models.ManyToManyField(to='holaserver.CarStatusTable', verbose_name='carId')),
            ],
            options={
                'verbose_name_plural': 'DriverDetailsTable',
            },
        ),
        migrations.AddField(
            model_name='cardetailstable',
            name='carId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='holaserver.CarStatusTable', verbose_name='carId'),
        ),
        migrations.AddField(
            model_name='cardetailstable',
            name='driverId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='holaserver.DriverDetailsTable', verbose_name='driverId'),
        ),
    ]
