# Generated by Django 2.1 on 2018-09-25 14:34

import Car
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carType', models.CharField(choices=[(Car.CarType(1), 1), (Car.CarType(2), 2), (Car.CarType(3), 3), (Car.CarType(4), 4), (Car.CarType(5), 5)], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('pastSevenDaysRideCount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DriverDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='carId', to='holaserver.CarDetails')),
            ],
        ),
    ]
