# Generated by Django 2.1.1 on 2018-09-26 05:16

import Car
import CarStatus
from django.db import migrations, models
import django.db.models.deletion
import holaserver.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarDetailsTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carAvailability', models.CharField(choices=[(CarStatus.CarAvailabilityStatus(1), 1), (CarStatus.CarAvailabilityStatus(2), 2), (CarStatus.CarAvailabilityStatus(3), 3), (CarStatus.CarAvailabilityStatus(4), 4), (CarStatus.CarAvailabilityStatus(5), 5)], default='CarAvailabilityStatus.UNKNOWN', max_length=100)),
                ('carType', models.CharField(choices=[(Car.CarType(1), 1), (Car.CarType(2), 2), (Car.CarType(3), 3), (Car.CarType(4), 4), (Car.CarType(5), 5)], default='CarType.UNKNOWN', max_length=100)),
                ('geoLocation', holaserver.models.GeoLocationField()),
            ],
        ),
        migrations.CreateModel(
            name='CustomerTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('pastSevenDaysRideCount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DriverDetailsTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='carId', to='holaserver.CarDetailsTable')),
            ],
        ),
    ]
