# Generated by Django 2.1.1 on 2018-09-29 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holaserver', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardetailstable',
            name='carAvailability',
            field=models.CharField(choices=[('UNKNOWN', 1), ('CAR_OFF_DUTY', 2), ('CAR_AVAILABLE', 3), ('CAR_ON_TRIP', 4), ('CAR_ON_TRIP_CLOSE_TO_COMPLETION', 5)], default='CarAvailabilityStatus.UNKNOWN', max_length=100),
        ),
        migrations.AlterField(
            model_name='cardetailstable',
            name='carType',
            field=models.CharField(choices=[('UNKNOWN', 1), ('CAR_TYPE_HATCHBACK', 2), ('CAR_TYPE_SEDAN', 3), ('CAR_TYPE_MINIVAN', 4), ('CAR_TYPE_AUTO', 5)], default='CarType.UNKNOWN', max_length=100),
        ),
    ]
