# Generated by Django 2.1.1 on 2018-09-30 13:27

from django.db import migrations, models
import django.db.models.deletion
import holaserver.models


class Migration(migrations.Migration):

    dependencies = [
        ('holaserver', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sourceLocation', holaserver.models.GeoLocationField()),
                ('destinationLocation', holaserver.models.GeoLocationField()),
                ('startTimeInEpochs', models.PositiveIntegerField()),
                ('endTimeInEpochs', models.PositiveIntegerField()),
                ('tripPrice', models.FloatField()),
                ('tripStatus', models.CharField(choices=[('UNKNOWN', 1), ('TRIP_STATUS_SCHEDULED', 2), ('TRIP_STATUS_ONGOING', 3), ('TRIP_STATUS_COMPLETED', 4), ('TRIP_STATUS_CANCELLED', 5)], default='TripStatus.UNKNOWN', max_length=100)),
                ('paymentMode', models.CharField(choices=[('UNKNOWN', 1), ('TRIP_STATUS_SCHEDULED', 2), ('TRIP_STATUS_ONGOING', 3), ('TRIP_STATUS_COMPLETED', 4), ('TRIP_STATUS_CANCELLED', 5)], default='PaymentMode.UNKNOWN', max_length=100)),
                ('rating', models.FloatField(default=0.0)),
                ('feedback', models.CharField(max_length=240)),
                ('carId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='holaserver.CarStatusTable', verbose_name='carId')),
                ('customerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='holaserver.CustomerTable', verbose_name='customerId')),
                ('driverId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='holaserver.DriverDetailsTable', verbose_name='driverId')),
            ],
            options={
                'verbose_name_plural': 'TripTable',
            },
        ),
    ]
