# Generated by Django 2.1.1 on 2018-10-02 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('holaserver', '0002_triptable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardetailstable',
            name='carId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='holaserver.CarStatusTable', verbose_name='carId'),
        ),
        migrations.AlterField(
            model_name='cardetailstable',
            name='driverId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='holaserver.DriverDetailsTable', verbose_name='driverId'),
        ),
        migrations.RemoveField(
            model_name='driverdetailstable',
            name='carId',
        ),
        migrations.AddField(
            model_name='driverdetailstable',
            name='carId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='holaserver.CarStatusTable', verbose_name='carId'),
        ),
        migrations.AlterField(
            model_name='triptable',
            name='carId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='holaserver.CarStatusTable', verbose_name='carId'),
        ),
        migrations.AlterField(
            model_name='triptable',
            name='customerId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='holaserver.CustomerTable', verbose_name='customerId'),
        ),
        migrations.AlterField(
            model_name='triptable',
            name='driverId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='holaserver.DriverDetailsTable', verbose_name='driverId'),
        ),
    ]
