# Generated by Django 2.1.1 on 2018-10-05 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('holaserver', '0006_auto_20181002_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='triptable',
            name='driverId',
        ),
    ]
