# Generated by Django 2.1.1 on 2018-10-05 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holaserver', '0007_remove_triptable_driverid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardetailstable',
            name='id',
        ),
        migrations.RemoveField(
            model_name='customertable',
            name='id',
        ),
        migrations.RemoveField(
            model_name='driverdetailstable',
            name='id',
        ),
        migrations.RemoveField(
            model_name='triptable',
            name='id',
        ),
        migrations.AddField(
            model_name='cardetailstable',
            name='carId',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='customertable',
            name='customerId',
            field=models.AutoField(default='1', primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driverdetailstable',
            name='driverId',
            field=models.AutoField(default='1', primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='triptable',
            name='tripId',
            field=models.AutoField(default='1', primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
